config/routes.rb
Spree::Core::Engine.routes.draw do
  post 'ajax/order/available_shipping_methods' => 'shipping_methods#index', :as => :available_shipping_methods
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

  checkout_flow do
    go_to_state :address
    go_to_state :delivery
    go_to_state :payment, :if => lambda { |order| order.payment_required? }
    go_to_state :confirm, :if => lambda { |order| order.confirmation_required? }
    go_to_state :complete, :if => lambda { |order| (order.payment_required? && order.payments.exists?) || !order.payment_required? }
    remove_transition :from => :delivery, :to => :confirm
  end

  def run_states
    ActiveRecord::Base.transaction do
      update!
      finalize!
      adjustments.each do |adj|
        adj.update!
      end
    end
  end

end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do

  skip_filter(:check_registration)

  helper 'spree/products'

  # change this to alias / spree
  def object_params
    unless params[:order][:payments_attributes].nil?
      if params[:payment_source].present? && source_params = params.delete(:payment_source)[params[:order][:payments_attributes].first[:payment_method_id].try(:underscore)]
        params[:order][:payments_attributes].first[:source_attributes] = source_params
      end
    end
    if (params[:order][:payments_attributes])
      params[:order][:payments_attributes].first[:amount] = @order.total
    end
    params[:order]
  end

  def update
    if @order.update_attributes(object_params) && params[:order][:shipping_method_id].present?
      if @order.next
        state_callback(:after)
      end
      @order.run_states
      fire_event('spree.checkout.update')
      flash.notice = t(:order_processed_successfully)
      flash[:commerce_tracking] = "nothing special"

      respond_with(@order, :location => completion_route)
    else
      flash[:error] = t(:please_select_shipping_method) if params[:order][:shipping_method_id].nil?
      respond_with(@order) { |format| format.html { render :template => 'spree/orders/one_page_checkout' } }
    end
  end
end

app/controllers/spree/orders_controller_decorator.rb
Spree::OrdersController.class_eval do

  def edit
    @order = current_order(true)
    associate_user
    @order.bill_address ||= Spree::Address.default
    @order.ship_address ||= Spree::Address.default
    # before_delivery
    @order.payments.destroy_all if request.put?
  end

  # change this to alias / spree
  def object_params
    if params[:payment_source].present? && source_params = params.delete(:payment_source)[params[:order][:payments_attributes].first[:payment_method_id].underscore]
      params[:order][:payments_attributes].first[:source_attributes] = source_params
    end
    if (params[:order][:payments_attributes])
      params[:order][:payments_attributes].first[:amount] = @order.total
    end
    params[:order]
  end

  private
    def before_delivery
      return if params[:order].present?
      @order.shipping_method ||= (@order.rate_hash.first && @order.rate_hash.first[:shipping_method])
    end

end

app/controllers/spree/shipping_methods_controller.rb
module Spree
  class ShippingMethodsController < Spree::StoreController

    layout nil

    ssl_allowed :index

    respond_to :json

    def index
      if params['state'].present? and params['country_id'].present?
        if current_order.ship_address.nil?
          current_order.ship_address = Address.create
        else
          current_order.ship_address.state_id = nil
          current_order.ship_address.state_name = nil
        end
        current_order.ship_address.country_id = params['country_id']
        Float(params['state']) != nil rescue false ? current_order.ship_address.state_id = params['state'] : current_order.ship_address.state_name = params['state']
        current_order.save(:validate => false)
        
        shipping_rates = []
        Spree::ShippingRate.find(current_order.tax_zone.shipping_methods.map(&:id)).each { |rate| shipping_rates.push( r = {name: rate.name, cost: rate.display_cost}) }
        
        render :json => shipping_rates
      else
        render :json => nil
      end
    end

  end
end

app/controllers/spree/user_sessions_controller_decorator.rb
Spree::UserSessionsController.class_eval do

  def create
    authenticate_spree_user!

    if spree_user_signed_in?
      respond_to do |format|
        format.html {
          flash[:success] = t(:logged_in_succesfully)
          redirect_to cart_path
        }
        format.js {
          user = resource.record
          render :json => {:ship_address => user.ship_address, :bill_address => user.bill_address}.to_json
        }
      end
    else
      flash.now[:error] = t('devise.failure.invalid')
      render :new
    end
  end

end

app/views/spree/orders/_checkout_form.html.erb
<%= form_for @order, :url => update_checkout_path('payment'), :html => { :id => "checkout_form_payment" } do |form| %>

  <div class="columns alpha eight" data-hook="billing_fieldset_wrapper">
    <fieldset id="billing" data-hook>
      <%= form.fields_for :bill_address do |bill_form| %>
        <legend align="center"><%= Spree.t(:billing_address) %></legend>
        <%= render :partial => 'spree/address/form', :locals => { :form => bill_form, :address_type => 'billing', :address => @order.bill_address } %>
      <% end %>
    </fieldset>
  </div>

  <div class="columns omega eight" data-hook="shipping_fieldset_wrapper">
    <fieldset id="shipping" data-hook>
      <%= form.fields_for :ship_address do |ship_form| %>
        <legend align="center"><%= Spree.t(:shipping_address) %></legend>
        <p class="field checkbox" data-hook="use_billing">
          <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
          <%= label_tag :order_use_billing, Spree.t(:use_billing_address), :id => 'use_billing' %>
        </p>
        <%= render :partial => 'spree/address/form', :locals => { :form => ship_form, :address_type => 'shipping', :address => @order.ship_address } %>
      <% end %>
    </fieldset>
  </div>
  

  <hr class="clear" />

  <div class='columns eight omega' data-hook='delivery_fieldset_wrapper' id="shipping_method_wrapper" >
    <fieldset id='shipping_method' class='clear-checkout variant-info' "data-hook"="" data-order="<%= @order.id %>" data-not-delivery="<%= t(:without_delivery) %>" data-url="<%= available_shipping_methods_url %>">
      <legend align="center"><%= t(:shipping_method) %></legend>
      <div id='methods'>
        <p class='field radios'>
        </p>
      </div>
      <% if Spree::Config[:shipping_instructions] %>
        <p id='minstrs' "data-hook"="">
          <%= form.label :special_instructions, t(:shipping_instructions) %>
          <br>
          <%= form.text_area :special_instructions, :cols => 40, :rows => 7 %>
      <% end %>
      <center>
        <button class="btn" id="check-shipping-methods" type="button"><%= t(:check_shipping_methods) %></button>
      </center>
    </fieldset>
  </div>

  <div class='omega eight columns'>
    <fieldset id="payment" class="variant-info" "data-hook">
      <legend align="center"><%= t(:payment_information) %></legend>
      <div "data-hook"="checkout_payment_step">
        <% @order.available_payment_methods.each do |method| %>
          <p>
            <label>
              <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id %>
              <%= t(method.name, :scope => :payment_methods, :default => method.name) %>
            </label>
          </p>
        <% end %>
        <ul id="payment-methods" "data-hook">
          <% @order.available_payment_methods.each do |method| %>
            <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
              <fieldset>
                <%= render :partial => "spree/checkout/payment/#{method.method_type}", :locals => { :payment_method => method } %>
              </fieldset>
            </li>
          <% end %>
        </ul>
        <br style="clear:both;">
        <div data-hook="coupon_code_field" data-hook></div>
      </div>
    </fieldset>
  </div>

  <br class="space" />
  <div class="form-buttons" "data-hook"="buttons">
    <%= submit_tag t(:checkout), :class => 'btn one-page-checkout-button', 'data-hook' => 'one_page_checout_button' %>
    <script>
      // disableSaveOnClick();
    </script>
  </div>
<% end %>

app/views/spree/orders/_line_items_fix.html.erb
<tbody id="line_items" data-hook>
  <%= render partial: 'line_item', collection: order_form.object.line_items, locals: {order_form: order_form} %>
</tbody>

app/views/spree/orders/one_page_checkout.html.erb
<% if !Spree::Auth::Config[:registration_step] || spree_user_signed_in? %>
  <%= render :partial => 'spree/orders/checkout_form' %>
<% else %>
  <%= render :template => 'spree/user_sessions/new' %>
<% end %>

app/views/spree/shared/_order_details.html.erb
<div class="row steps-data">

  <% if order.has_step?("address") %>
    <div class="columns alpha four">
      <h6><%= t(:shipping_address) %> <%= link_to "(#{t(:edit)})", cart_path unless @order.completed? %></h6>
      <div class="address">
        <%= order.ship_address %>
      </div>
    </div>

    <div class="columns alpha four">
      <h6><%= t(:billing_address) %> <%= link_to "(#{t(:edit)})", cart_path unless @order.completed? %></h6>
      <div class="address">
        <%= order.bill_address %>
      </div>
    </div>

    <% if @order.has_step?("delivery") %>
      <div class="columns alpha four">
        <h6><%= t(:shipping_method) %> <%= link_to "(#{t(:edit)})", cart_path unless @order.completed? %></h6>
        <div class="delivery">
          <%= order.shipping_method.name %>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="columns omega four">
    <h6><%= t(:payment_information) %> <%= link_to "(#{t(:edit)})", cart_path unless @order.completed? %></h6>
    <div class="payment-info">
      <%= render order.payments.valid %>
    </div>
  </div>

</div>

<hr />

<table class="index columns alpha omega sixteen" data-hook="order_details">
  <col width="15%" valign="middle" halign="center">
  <col width="70%" valign="middle">
  <col width="5%" valign="middle" halign="center">
  <col width="5%" valign="middle" halign="center">
  <col width="5%" valign="middle" halign="center">

  <thead id="line-items" data-hook>
    <tr data-hook="order_details_line_items_headers">
      <th colspan="2"><%= t(:item) %></th>
      <th class="price"><%= t(:price) %></th>
      <th class="qty"><%= t(:qty) %></th>
      <th class="total"><span><%= t(:total) %></span></th>
    </tr>
  </thead>

  <tbody id="line-items" data-hook>
    <% @order.line_items.each do |item| %>
      <tr data-hook="order_details_line_item_row">
        <td data-hook="order_item_image">
          <% if item.variant.images.length == 0 %>
            <%= link_to small_image(item.variant.product), item.variant.product %>
          <% else %>
            <%= link_to image_tag(item.variant.images.first.attachment.url(:small)), item.variant.product %>
          <% end %>
        </td>
        <td data-hook="order_item_description">
          <h4><%= item.variant.product.name %></h4>
          <%= truncated_product_description(item.variant.product) %>
          <%= "(" + item.variant.options_text + ")" unless item.variant.option_values.empty? %>
        </td>
        <td data-hook="order_item_price" class="price"><span><%= item.variant.display_amount.to_html %></span></td>
        <td data-hook="order_item_qty"><%= item.quantity %></td>
        <td data-hook="order_item_total" class="total"><span><%= item.display_amount.to_html %></span></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot id="order-total" data-hook="order_details_total">
    <tr class="total">
      <td colspan="4"><b><%= t(:order_total) %>:</b></td>
      <td class="total"><span id="order_total"><%= @order.display_total.to_html %></span></td>
    </tr>
  </tfoot>
  <% if order.price_adjustment_totals.present? %>
    <tfoot id="price-adjustments" data-hook="order_details_price_adjustments">
      <% @order.price_adjustment_totals.each do |key, total| %>
        <tr class="total">
          <td colspan="4"><strong><%= key %></strong></td>
          <td class="total"><span><%= total %></span></td>
        </tr>
      <% end %>
    </tfoot>
  <% end %>
  <tfoot id="subtotal" data-hook="order_details_subtotal">
    <tr class="total" id="subtotal-row">
      <td colspan="4"><b><%= t(:subtotal) %>:</b></td>
      <td class="total"><span><%= @order.display_item_total.to_html %></span></td>
    </tr>
  </tfoot>
  <tfoot id="order-charges" data-hook="order_details_adjustments">
    <% @order.adjustments.eligible.each do |adjustment| %>
    <% next if (adjustment.originator_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
      <tr class="total">
        <td colspan="4"><strong><%= adjustment.label %></strong></td>
        <td class="total"><span><%= adjustment.display_amount.to_html %></span></td>
      </tr>
    <% end %>
  </tfoot>
</table>